### ISSUE TITLE
Shop style/thumbnail trigger one another.

### ISSUE THREAD

**Issue by kitajchuk** [thisdesign/baldface-sqs#1]
We got the thumbs triggering the style events with this commit: 09df4e5c0357f52c839aae76c476f1b6037da4fe

Next we need the style events to trigger the thumbs event which is wrapped up inside a Carousel container.

Recommendation: store a reference of the CarouselThumbs instance with its element data so you can reach it from the ShopProduct.

**Comment by metamas** [comment]
Running locally on my end and I've got the following error throwing every time I click a thumbnail. I haven't made any changes yet. I'm going to start debugging it now. Just thought I'd put this here if you had a quick answer.
![screen shot 2018-03-23 at 11 07 49 am](https://user-images.githubusercontent.com/2520253/37846587-489c6a94-2e8b-11e8-84d1-a9bd9878be62.png)

**Comment by kitajchuk** [comment]
weird that wasn't happening yesterday...

**Comment by metamas** [comment]
It's happening here:
```javascript
this.element.on( "click", ".js-carousel-thumb", ( e ) => {
    this.doShopStyleClick({
        target: this.shopStyles[ $( e.target ).index() ]
     });
});
```

Specifically, `this.shopStyles[ $( e.target ).index() ]` is coming back undefined.

**Comment by kitajchuk** [comment]
@metamas It's an async load+template render situation I just realized. The `ShopProduct` constructor has this line in it:

`this.shopStyles = this.element.find( ".js-shop-style" );`

But those nodes don't exist yet since the js view has not rendered yet. We can move that line of code down into the `loadVariants` method directly after the element's `innerHTML` is applied.

Make sense?

**Comment by metamas** [comment]
Yeah makes sense. Trying to test it now. My shit is just running so slow for some reason...

**Comment by kitajchuk** [comment]
@metamas Squarespace dev server is a little slow in general :P

**Comment by metamas** [comment]
I've got the `watch` and `server` scripts  running in their own terminal windows. That's how dev is supposed work with `boxen`, right?

**Comment by kitajchuk** [comment]
You can just use `npm start` to run it parallel in one window.

**Comment by kitajchuk** [comment]
Lol sorry clicked wrong button and closed the ticket for a sec :/

**Comment by metamas** [comment]
Lol, of course. I totally just wrote off `start` after going through the setup.

**Comment by kitajchuk** [comment]
If you're working on something I set up it will always be `npm start` regardless of the project :)

**Comment by metamas** [comment]
As it should be :)

**Comment by metamas** [comment]
All is well in baldface land again. Now, I'll get started on the other half. Thanks @kitajchuk. I'll see you in a bit!

**Comment by kitajchuk** [comment]
@metamas thanks dude! let me know when you've deployed anything to Squarespace :)

**Comment by metamas** [comment]
@kitajchuk I think I've got all the main pieces in place with this commit: 2391c7cdc8dcf516456b5c017999bc42cd23c67f

But it's not working yet, and I think it's because I'm either misunderstanding the Hobo `data()` API, or some scope amongst `ShopProduct` and `CarouselThumbs`. Peep it and tell me what you see.

@tobygrubb Sorry I ended up getting back to this later than intended. It'll be sorted soon. Hope you're feeling better.

**Comment by tobygrubb** [comment]
All good. Appreciate your diligence.
I’m sadly still bed-ridden

**Comment by metamas** [comment]
@kitajchuk Also, I did initially consider the path of manually triggering the event via Hobo's `trigger()` or with something like
```javascript
const event = new Event('click');
elem.dispatchEvent(event);
```
...from within the `doThumbClick` function, but instead figured your recommendation of exposing the `self`  reference entailed just mirroring the `CarouselThumb` event handler behavior, and perhaps abstracting it as a method once I had it working (?).

Anyway, I'm curious to know if either of the above options would even work. I'll explore them a bit, if I don't hear from you first.

**Comment by kitajchuk** [comment]
@metamas you were super close man! I went ahead and tweaked it to the finish line with this commit: 160cfa3225aa2704029530352b225fbda3ee24bb.

The last hangup there had to do with where the data was being stored and how it was trying to be accessed. The `data` API works directly with [DOMStringMap](https://developer.mozilla.org/en-US/docs/Web/API/DOMStringMap). If you think of it like `key=>value` pairing then the key would be the actual DOMElement and the value would be the data payload.

So, in the CarouselThumbs class we're storing the `self` reference with the root element for that Class, `js-carousel`. Then in the handler where we try to trigger the thumb click we access the data again from the root element of the CarouselThumbs Class. I noticed you were calling the `data` method here on the thumb itself rather than the carousel container, which is where the data is stored.

That's it man. Take a look at the commit changes and I think it should make sense. Good work dude! Do a `git pull origin master` and test it out locally too. Then use `npm run deploy` to push the code to Squarespace. You can check the `package.json` file to see what all the commands are but that and `npm start` are all you really need.

Once the code is deployed feel free to close this issue 👍

**Comment by kitajchuk** [comment]
@tobygrubb feel better dude!

**Comment by metamas** [comment]
@kitajchuk Thank you! Everything is running smooth on my end now.

Like you explained, my confusion was indeed that the `this.element` inside of  the **CarouselThumbs** constructor was actually the root element `js-carousel` and not a `js-carousel-thumb` element that it was being passed from within the **CarouselController** init.

Shows that my thinking in classes is a bit rusty — been doing a lot of functional rendering with template components in other projects :p

**Comment by metamas** [comment]
@kitajchuk Problem running `deploy`:
![screen shot 2018-03-26 at 9 42 45 am](https://user-images.githubusercontent.com/2520253/37919963-5becb918-30da-11e8-8df9-d3315e30d10a.png)

**Comment by metamas** [comment]
@kitajchuk I also tried changing `sqs_site_url=https://baldface.net` inside `.nprc` to `sqs_site_url=https://baldface-lodge.squarespace.com`, with no success.

**Comment by kitajchuk** [comment]
@metamas you should have an invite to the Baldface Squarespace site now as an Admin — confirm that so you have permissions for the site. Then do these steps:

1. Next, create a file in the root of the project directory: `touch .npmrc`. This is an ignored file, though it probably doesn't need to be lol.
2. Add this to the file: `sqs_site_url=https://baldface-lodge.squarespace.com`.
3. In your `node_modules` folder open the file `@squarespace/toolbelt/build/utils/deployment.js`.
4. On line 223 of this file add additional options for the git command to allow unrelated histories so the line looks like this: `repo.pull([remote, 'master'], { 'strategy': 'ours', 'allow-unrelated-histories': '' }, finishWithGitResult(repo, resolve, reject));`.

That should get you going for the deployments 👍

**Comment by metamas** [comment]
@kitajchuk Success! Does it usually take a bit for pushed changes to appear on the live site?

**Comment by kitajchuk** [comment]
@metamas clear your cache for the site and test it again. In Chrome I have cache disabled while dev tools are open.

**Comment by metamas** [comment]
@kitajchuk Thanks for dev tools settings tip. Closing this issue, now.

**Comment by kitajchuk** [comment]
WhooT!

**Comment by tobygrubb** [comment]
Bam!!!!

(( authored by thumbs ))


Toby Grubb 
Partner/Creative Director
-
toby@this.design
802.318.1247
